=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/aim.configuration.dtd
<!ENTITY % html "(#PCDATA|br|i|b|code|span|p|ul)*">

<!ELEMENT block (description, dependencies?, properties, createdEntities?, createdRelations?)>

<!ATTLIST block
  tech CDATA #REQUIRED
  subtech CDATA #REQUIRED
  descriptor CDATA #REQUIRED
  label CDATA #IMPLIED
  created CDATA #IMPLIED
  lastModified CDATA #IMPLIED
>

<!ELEMENT dependencies (dependency*)>
<!ELEMENT dependency (#PCDATA)>

<!ELEMENT properties (property*)>

<!ELEMENT property (name, example?, description, possible?)>
<!ATTLIST property
  id ID #REQUIRED
  type (string|bool|enum|list) "string"
  subtype (string|regexp|antPattern) "string"
  separator CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT description %html;>
<!ELEMENT possible (enumval*)>
<!ELEMENT enumval %html;>
<!ATTLIST enumval
  name CDATA #REQUIRED
>

<!ELEMENT br EMPTY>
<!ELEMENT p %html;>
<!ELEMENT i %html;>
<!ELEMENT b %html;>
<!ELEMENT code %html;>
<!ELEMENT span %html;>
<!ATTLIST span
  class CDATA #IMPLIED
>
<!ELEMENT ul (li*)>
<!ELEMENT li (#PCDATA)>

<!ELEMENT createdEntities (values,description)>
<!ELEMENT createdRelations (values,description)>
<!ELEMENT values (#PCDATA)>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/j2ee/aim.spring.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='j2ee' subtech='spring' descriptor='j2ee/aim.spring.xml' label='Models beans in Spring XML descriptors'>
  <description>
    Process parsed Spring descriptors looking for bean definitions, and dependencies between them.
    <br/>
    Specific Spring modules, like WebFlow are also processed.
    <br/>
    For certain beans, extended entities and relations may be modeled.
  </description>

  <dependencies>
    <dependency>j2ee/java</dependency>
  </dependencies>

  <properties>

    <property id='aim.j2ee.rule.spring.beans.active' type='bool'>
      <name>springActive</name>
      <example>false</example>
      <description>If true, normal Spring XML descriptors are processed.</description>
    </property>

    <property id='aim.j2ee.rule.spring.webflow.active' type='bool'>
      <name>webflowActive</name>
      <example>false</example>
      <description>If true, Spring WebFlow descriptors are processed.</description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.software' type='string'>
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>Name of the software (application) where Spring beans are placed.</description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.filter' type='list' subtype='antPattern'>
      <name>filter</name>
      <example>**/*.xml</example>
      <description>Ant pattern(s) to select which normal Spring XML descriptors to process.</description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.processor.jaxProxy.active' type='bool'>
      <name>jaxProxyActive</name>
      <example>true</example>
      <description>If true, Spring JAX-RPC and JAX-WS proxy beans (WebService proxies) will be processed.</description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.processor.jaxProxy.acceptUnresolved' type='bool'>
      <name>jaxProxyAcceptUnresolved</name>
      <example>false</example>
      <description>If true, unresolved target web services for JAX-* proxies will be created as if they belong to the bean's software.</description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.processor.xfireProxy.active' type='bool'>
      <name>xfireProxyActive</name>
      <example>true</example>
      <description>If true, Spring XFireClientFactoryBean beans (XFire client proxies) will be processed</description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.processor.xfireProxy.acceptUnresolved' type='bool'>
      <name>acceptUnresolved</name>
      <example>false</example>
      <description>
        If true, unresolved target web services for XFire proxies will be created as if they belong to the bean's software
      </description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.processor.xfireExporter.active' type='bool'>
      <name>xfireExporteractive</name>
      <example>true</example>
      <description>
        If true, Spring XFireExporter beans (XFire exposed web services) will be processed
      </description>
    </property>

    <property id='aim.j2ee.rule.spring.beans.extraProcessors' type='string'>
      <name>extraProcessors</name>
      <example></example>
      <description>
        Comma-separated list of SpringProcessor bean names/ids that will be used as extra bean processors.
        Empty means that no additional bean processor will be registered.
      </description>
    </property>

    <property id='aim.j2ee.rule.spring.webflow.filter' type='list' subtype='antPattern'>
      <name>filter</name>
      <example>**-flow.xml</example>
      <description>Ant pattern(s) to select which Spring WebFlow descriptors to process.</description>
    </property>

    <property id='aim.j2ee.rule.spring.webflow.software' type='string'>
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>Name of the software (application) where Spring WebFlow entities are placed.</description>
    </property>

    <property id='aim.j2ee.rule.spring.webflow.parseBeanImports' type='bool'>
      <name>parseBeanImports</name>
      <example>true</example>
      <description>Decides if bean-imports elements should be processed in Spring WebFlow descriptors.</description>
    </property>

  </properties>

  <createdEntities>
    <values>
      configuration(descriptor),element(bean),flow,other(flow state),page(view)
    </values>
    <description>
      Configuration (per Spring descriptor file), element (for each Spring bean declared).
      <br/>
      For Spring WebFlow, flow, flow states (other), and views (page) are modeled.
    </description>
  </createdEntities>

  <createdRelations>
    <values>
      configuration(Spring descriptor)->element(bean)-configuration,
      bean-uses->bean,
      flow-contains->other(flow state),
      other(flow state)-transition->other(flow state),
      other(flow state)-calls->page(view)
    </values>
    <description>
      <i>uses</i> relation (between injection dependencies between beans),
      <i>configures</i> relation between beans and the descriptors where they are declared.
      <br/>
      For WebFlow, each flow contains flow states (modeled as other).
      Each flow state may transition to the next flow state.
      A Flow state may call a view (modeled as page)
    </description>
  </createdRelations>

  <importantConfigurations activation="aim.j2ee.rule.spring.beans.active">
    <alternative><value>aim.j2ee.rule.spring.webflow.active=false</value></alternative>
  </importantConfigurations>

</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/legacy/aim.natural.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='legacy' subtech='natural' descriptor='legacy/aim.natural.xml' label='Process Software AG Natural / Adabas technology'>
  <description>
    Process Software AG Natural / Adabas technology (Natural code and references to Adabas entities).
  </description>

  <properties>

    <property id='aim.natural.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>Enable for processing Natural code.</description>
    </property>

    <property id='aim.natural.rule.view.active' type='bool'>
      <name>nslActive</name>
      <example>false</example>
      <description>
        Enable for processing Local Data Area descriptors (e.g. NSL files) and process references to Adabas views.
        Often, NSL files are the unique resource available to infer relations between Natural code and Adabas entities.
      </description>
    </property>

    <property id='aim.natural.software' type='string'>
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>Application/module name for Natural code, if no global sofware resolver.</description>
    </property>

    <property id='aim.natural.dbsystem' type='string'>
      <name>dbsystem</name>
      <example>${aim.common.database.dbsystem}</example>
      <description>Database system (e.g. Adabas).</description>
    </property>

    <property id='aim.natural.dbname' type='string'>
      <name>dbname</name>
      <example>${aim.common.database.dbname}</example>
      <description>Database name.</description>
    </property>

    <property id='aim.natural.ignoreCase' type='string'>
      <name>ignoreCase</name>
      <example>${aim.common.ignoreCase}</example>
      <description>If true, case is ignored in entity names found in Natural code items.</description>
    </property>

    <property id='aim.natural.rule.processDatabaseOperations' type='bool'>
      <name>processDatabaseOperations</name>
      <example>true</example>
      <description>If set to true, database operations (e.g. Adabas) will be processed.</description>
    </property>

    <property id='aim.natural.filter' type='enum'>
      <name>filter</name>
      <example>default</example>
      <description>Strategy to use for selecting Natural files to process.</description>
      <possible>
        <enumval name='default'>Accept Natural files with extensions from natural technology.</enumval>
        <enumval name='pattern'>Process Natural files matching patterns in the <code>patterns</code> property.</enumval>
      </possible>

    </property>

    <property id='aim.natural.filter.pattern' type='list' subtype='antPattern'>
      <name>patterns</name>
      <example>**/*.nsp,**/*.nsn,**/*.nss,**/*.nsh,**/*.nsc</example>
      <description>If <code>filter</code> set to pattern, select the following comma-separated Ant patterns.</description>
    </property>

    <property id='aim.natural.resolver.file.basedir' type='string'>
      <name>resolveBasedir</name>
      <example>${aim.common.srcdir}</example>
      <description>
        Directories under <code>resolveBasedir</code> matching <code>resolvePatterns</code>
        will be examined for Natural code when resolving program dependencies.
      </description>
    </property>

    <property id='aim.natural.resolver.file.patterns' type='list' subtype='antPattern'>
      <name>resolvePatterns</name>
      <example>**</example>
      <description>
        Ant patterns for matching subdirectories (relative to <code>resolveBasedir</code>)
        where program dependencies will be resolved.
      </description>
    </property>

    <property id='aim.natural.rule.view.pattern' type='string'>
      <name>viewNamePattern</name>
      <example>\\s*\\d+\\s+V\\s\\d+\\s+(\\S+)\\s+(\\S+)\\s*</example>
      <description>
        Regular expression for extracting view names from local data area descriptors.
        <br/>
        First capturing group is the alias for the view, second capturing group is the view name.
      </description>
    </property>

    <property id='aim.natural.rule.view.include' type='list' subtype='antPattern'>
      <name>localDataAreaPatterns</name>
      <example>*.NSL,**/*.NSL</example>
      <description>Patterns for local data area descriptors.</description>
    </property>

  </properties>

  <createdEntities>
    <values>
      program(program|subprogram|subroutine|helproutine|copy),
      resource(data area),
      page(map),
      window,
      databaseItem(Adabas db),
      sql(Adabas operation),
      table(Adabas view)
    </values>
    <description>
      Natural code elements (program, subprogram, subroutine, helproutine, copy) are modeled as <i>program</i>.
      Data areas (local, global, parameter) are modeled as <i>resource</i>.
      Maps ("screen layout") are modeled as <i>page</i>, while Natural Windows are modeled as <i>window</i>.
      <br/>
      Adabas entities ("views") are modeled as <i>table</i>, and placed in a <i>databaseItem</i>
      representing an Adabas database.
      <br/>
      Each database operation (READ, FIND, HISTOGRAM, GET, STORE, UPDATE, DELETE) is modeled as sql.
    </description>
  </createdEntities>

  <createdRelations>
    <values>
      program-calls->program,
      program-includes->program(copy),
      program-contains->window,
      program-uses->page(map),
      program-calls->sql(Natural operation),
      sql-uses->table(Adabas view)
    </values>
    <description>
      For each Natural element (program, subprogram, subroutine, helproutine, copy), outgoing dependencies
      (calls, includes), and references to windows and maps ("screen layout")  are modeled.
      <br/>
      Dependencies between Natural and Adabas are modeled this way: <i>program -calls -> sql(Natural operation) -uses-> table(Adabas view)</i>.
    </description>
  </createdRelations>

  <importantConfigurations activation="aim.natural.rule.active">
    <alternative><value>aim.natural.rule.view.active=true</value></alternative>
  </importantConfigurations>

</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/j2ee/aim.webservice.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='j2ee' subtech='webservice' descriptor='j2ee/aim.webservice.xml' label='WebService processing in J2EE code'>
  <description>
    Discovers web services (either server-side, or client proxies/stubs declarations) and relations.
    <br/>
    Currently this module detects:
    <ul>
      <li>JAX-WS web services declared via annotations (JSR-181) in Java classes.</li>
      <li>Web services declared in WSDU descriptors generated by Borland's JBuilder WebServicesDesigner.</li>
      <li>Web services declared in Apache Axis WSDD descriptors.</li>
    </ul>
  </description>

  <dependencies>
    <dependency>j2ee/java</dependency>
  </dependencies>

  <properties>
    <property id='aim.j2ee.webservice.rule.jaxws.active' type='bool'>
      <name>jaxwsActive</name>
      <example>false</example>
      <description>Set to true to activate discovering web services in Java classes with JAX-WS (JSR-181) annotations.</description>
    </property>

    <property id='aim.j2ee.webservice.rule.jbuilder.active' type='bool'>
      <name>jbuilderActive</name>
      <example>false</example>
      <description>Set to true to activate discovering web services and class dependencies in WSDU descriptors from JBuilder WebServicesDesigner.</description>
    </property>

    <property id='aim.j2ee.webservice.rule.axisWsdd.active' type='bool'>
      <name>axisWsddActive</name>
      <example>false</example>
      <description>Set to true to activate discovering web services and class dependencies in Apache Axis WSDD deployment descriptors.</description>
    </property>

    <property id='aim.j2ee.webservice.rule.jaxws.processWebServiceClient' type='bool'>
      <name>processWebServiceClient</name>
      <example>true</example>
      <description>If true, @WebServiceClient annotations will be processed (JAX-WS client proxies).</description>
    </property>

    <property id='aim.j2ee.webservice.rule.jaxws.processWebServiceServer' type='bool'>
      <name>processWebServiceServer</name>
      <example>true</example>
      <description>If true, @WebService annotations will be processed (JAX-WS service implementations).</description>
    </property>

    <property id='aim.j2ee.webservice.rule.jaxws.createWebServiceMethods' type='bool'>
      <name>createWebServiceMethods</name>
      <example>false</example>
      <description>If set to true, JAX-WS webservice methods (annotated with @WebMethod) will be created, contained in the Web Service.</description>
    </property>

    <property id='aim.j2ee.webservice.rule.jaxws.createUnresolvedWebServices' type='bool'>
      <name>createUnresolvedWebServices</name>
      <example>false</example>
      <description>If set to true, webservices used in proxies that cannot be resolved are created in the same proxy software.</description>
    </property>

    <property id="aim.j2ee.webservice.filter.jbuilder" type='list' subtype="antPattern">
      <name>wsduPatterns</name>
      <example>**/*.wsdu</example>
      <description>Ant patterns to match which WSDU files to process.</description>
    </property>

    <property id='aim.j2ee.webservice.rule.jbuilder.createUnresolvedWebServices' type='bool'>
      <name>jbuilder.createUnresolvedWebServices</name>
      <example>false</example>
      <description>
        If set to true, webservices referenced in .wsdu that cannot be resolved are created in the
        same software that contains the descriptor.
      </description>
    </property>

    <property id='aim.j2ee.webservice.rule.axisWsdd.createWebServiceMethods' type='bool'>
      <name>axisWsdd.createWebServiceMethods</name>
      <example>false</example>
      <description>If set to true, webservice methods (operations for each service in WSDD) will be created, contained in the Web Service.</description>
    </property>

    <property id='aim.j2ee.webservice.rule.axisWsdd.software' type='string'>
      <name>axisWsdd.software</name>
      <example>${aim.common.software}</example>
      <description>
        Default (fallback) software name. Please note that global software resolvers could be used to
        resolve the software where WSDD file lives.
      </description>
    </property>

    <property id="aim.j2ee.webservice.filter.axisWsdd" type='list' subtype="antPattern">
      <name>wsddPatterns</name>
      <example>**/*.wsdd</example>
      <description>Ant patterns to match which Apache Axis WSDD files to process.</description>
    </property>

  </properties>

  <createdEntities>
    <values>webService,operation,class,configuration</values>
    <description>
      For each web service found, a webService component is created. Java client stubs and service interface classes
      are modeled as well with a class component.
      <br/>
      The property <code>createWebServiceMethods</code>, when true, controls whether an operation contained
      in the web service is created each (annotated) web service method.
      <br/>
      For web service descriptors, configuration components are created.
    </description>
  </createdEntities>

  <createdRelations>
    <values>
      class(proxy)-uses->webService,
      webService-uses->class(implementation classes),
      webService-implementedBy->class(service class),
      configuration-configures->webService
    </values>
    <description>
      Creates relations between proxy class and web service, and between web service and server-side classes
      (<i>implementedBy</i> with service interface or service implementation, <i>uses</i> for related classes).
    </description>
  </createdRelations>

  <importantConfigurations>
    <alternative>
      <value>aim.j2ee.webservice.rule.jaxws.active=true</value>
    </alternative>
    <alternative>
      <value>aim.j2ee.webservice.rule.jaxws.active=true</value>
      <value>aim.j2ee.webservice.rule.jaxws.createWebServiceMethods=true</value>
    </alternative>
    <alternative>
      <value>aim.j2ee.webservice.rule.jbuilder.active=true</value>
    </alternative>
    <alternative>
      <value>aim.j2ee.webservice.rule.axisWsdd.active=true</value>
    </alternative>
    <alternative>
      <value>aim.j2ee.webservice.rule.axisWsdd.active=true</value>
      <value>aim.j2ee.webservice.rule.axisWsdd.createWebServiceMethods=true</value>
    </alternative>
  </importantConfigurations>

</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/php/aim.php.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='php' subtech='php' descriptor='php/aim.php.xml' label='Process PHP classes'>
  <description>
    Models PHP programs and functions, classes (and optionally, methods), resolving dependencies in the PHP language:
    method calls, object instantiations, inheritance, reference to type fields.
    <br/>
    To activate registration of methods in the model, the property <code>methodsPredicate</code> could be set.
    Registering all class methods as components is discouraged, as model could have a huge number of components.
  </description>

  <properties>
    <property id='aim.php.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>Activation for PHP analysis.</description>
    </property>

    <property id='aim.php.software' type='string'>
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>
        Default (fallback) software name. Please note that global software resolvers could be used to
        resolve the software where each PHP file lives.
      </description>
    </property>

    <property id='aim.php.registerMethods' type='bool'>
      <name>registerMethods</name>
      <example>true</example>
      <description>Register class methods and their dependencies (calls).</description>
    </property>

    <property id='aim.php.registerFunctions' type='bool'>
      <name>registerFunctions</name>
      <example>true</example>
      <description>Register functions and their dependencies (calls).</description>
    </property>

    <property id='aim.php.resolveCalls' type='bool'>
      <name>resolveCalls</name>
      <example>true</example>
      <description>When true, function/method calls between PHP entities are processed.</description>
    </property>

    <property id='aim.php.resolveFieldReferences' type='bool'>
      <name>resolveFieldReferences</name>
      <example>true</example>
      <description>When true, class field usages are processed.</description>
    </property>

    <property id='aim.php.resolveInheritance' type='bool'>
      <name>resolveInheritance</name>
      <example>true</example>
      <description>When true, class/trait/interface inheritance dependencies are processed (extends from parent class, inherits from interface).</description>
    </property>

    <property id='aim.php.resolveInstantiations' type='bool'>
      <name>resolveInstantiations</name>
      <example>true</example>
      <description>hen true, object instantiations are processed (usages of the <code>new</code> operator).</description>
    </property>

    <property id='aim.php.addCodeToRelations' type='bool'>
      <name>addCodeToRelations</name>
      <example>${aim.common.addCodeToRelations}</example>
      <description>If true, matching PHP code will be added to relations.</description>
    </property>

    <property id='aim.php.resolveArtifacts' type='bool'>
      <name>resolveArtifacts</name>
      <example>${aim.common.resolveArtifacts}</example>
      <description>If true, artifacts will be resolved.</description>
    </property>

    <property id='aim.php.resolver' type='enum'>
      <name>resolver</name>
      <example>existing</example>
      <description>
        Which class resolver to use for resolving dependencies on target classes.
      </description>
      <possible>
        <enumval name="existing">Resolve only relations to classes found in analyzed code.</enumval>
        <enumval name="matching">Resolve only relations to classes matching <code>matching.patterns</code>.</enumval>
      </possible>
    </property>

    <property id='aim.php.matching.patterns' type='list' subtype='regexp'>
      <name>matching.patterns</name>
      <example>.+</example>
      <description>
        If <code>resolver</code> is set to <i>matching</i>, the package patterns (regular expressions) to use.
      </description>
    </property>

    <property id="aim.php.methodPredicate" type="enum">
      <name>methodPredicate</name>
      <example>nonPrivateMagicGetterSetter</example>
      <description>Which methods to model? (when registerMethods=true)</description>
      <possible>
        <enumval name="nonPrivateMagicGetterSetter">ignore private, "magic" and getter/setter methods</enumval>
        <enumval name="nonPrivateMagic">ignore private or "magic" methods</enumval>
        <enumval name="any">register all methods</enumval>
      </possible>
    </property>

    <property id="aim.php.filter" type="enum">
      <name>filter</name>
      <example>default</example>
      <description>Filter to use (default, pattern) for PHP code files</description>
      <possible>
        <enumval name="default">Use PHP extensions to match PHP source files.</enumval>
        <enumval name="pattern">Use Ant patterns given in the <code>filter.pattern</code> property.</enumval>
      </possible>
    </property>

    <property id='aim.php.filter.pattern' type='list' subtype='antPattern'>
      <name>filter.pattern</name>
      <example>**/*.php, **/*.php3, **/*.php4, **/*.php5, **/*.php6, **/*.phps, **/*.phtml</example>
      <description>Filter (Ant patterns) for PHP sources, when filter = pattern</description>
    </property>

    <property id="aim.php.resolveSQL" type="bool">
      <name>resolveSQL</name>
      <example>true</example>
      <description>If true, resolve dependencies in embedded SQL code; if false, no SQL code is processed</description>
    </property>

    <property id="aim.php.createSqlComponents" type="bool">
      <name>createSqlComponents</name>
      <example>true</example>
      <description>If true, create intermediate component for each SQL statement detected, linked to the source component and to the database objects.
       If false, no component is created for SQL statement, and direct dependencies are created between source component and database objects.</description>
    </property>

    <property id="aim.php.dbtype" type="enum">
      <name>dbtype</name>
      <example>sql92</example>
      <description>The dialect of embedded SQL in PHP code (sql92 or oracle)</description>
      <possible>
        <enumval name="sql92">SQL-92 SQL code</enumval>
        <enumval name="oracle">Oracle SQL code</enumval>
      </possible>
    </property>

    <property id="aim.php.dbsystem" type="string">
      <name>dbsystem</name>
      <example>${aim.common.database.dbsystem}</example>
      <description>The name for default software to contain database objects, when not resolved by a global database resolver.</description>
    </property>

    <property id="aim.php.dbname" type="string">
      <name>dbname</name>
      <example>${aim.common.database.dbname}</example>
      <description>The name for database component to contain database objects, when not resolved by a global database resolver.</description>
    </property>

    <property id="aim.php.ignoreSQLCase" type="bool">
      <name>ignoreSQLCase</name>
      <example>true</example>
      <description>If true, ignore case for database objects; if false, keep case found in SQL statements.</description>
    </property>

  </properties>

  <createdEntities>
    <values>program, function, class, operation (method), sql, table|view</values>
    <description>
      Creates program components for each PHP file.
      For classes, create class components and, if <code>registerMethods=true</code>, methods are registered.
      If <code>registerFunctions=true</code>, function components are registered.
      If <code>resolveSQL=true</code>, embedded SQL is processed and dependencies with database objects resolved.
      (when <code>createSqlComponents=true</code>, intermediate sql components are created).
    </description>
  </createdEntities>

  <createdRelations>
    <values>
      program-includes->program,
      program-contains->class,
      class-contains->operation,
      class|operation-inherits|calls|uses|instantiates|references->class|operation,

    </values>
    <description>
      Between classes, resolves inheritance, method calls, variable references, object instantiations and type references.
      When an operation is modeled (according to the <code>registerMethods</code> and <code>registerFunctions</code>),
      it acts as the source/target of the relation. Operation is contained in the class that declares the method, or
      in the PHP program that declares a normal function.
    </description>
  </createdRelations>
  
  
  <!--importantConfigurations activation="aim.php.rule.active" /-->
  <importantConfigurations>
    <alternative>
      <value>aim.php.rule.active=true</value>
      <value>aim.php.registerMethods=false</value>
      <value>aim.php.registerFunctions=false</value>
    </alternative>
    <alternative>
      <value>aim.php.rule.active=true</value>
      <value>aim.php.registerMethods=true</value>
      <value>aim.php.registerFunctions=true</value>
    </alternative>
  </importantConfigurations>
  
</block>
