=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/aim.configuration.dtd
<!ENTITY % html "(#PCDATA|br|i|b|code|span|p|ul)*">

<!ELEMENT block (description, dependencies?, properties, createdEntities?, createdRelations?)>

<!ATTLIST block
  tech CDATA #REQUIRED
  subtech CDATA #REQUIRED
  descriptor CDATA #REQUIRED
  label CDATA #IMPLIED
  created CDATA #IMPLIED
  lastModified CDATA #IMPLIED
>

<!ELEMENT dependencies (dependency*)>
<!ELEMENT dependency (#PCDATA)>

<!ELEMENT properties (property*)>

<!ELEMENT property (name, example?, description, possible?)>
<!ATTLIST property
  id ID #REQUIRED
  type (string|bool|enum|list) "string"
  subtype (string|regexp|antPattern) "string"
  separator CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT description %html;>
<!ELEMENT possible (enumval*)>
<!ELEMENT enumval %html;>
<!ATTLIST enumval
  name CDATA #REQUIRED
>

<!ELEMENT br EMPTY>
<!ELEMENT p %html;>
<!ELEMENT i %html;>
<!ELEMENT b %html;>
<!ELEMENT code %html;>
<!ELEMENT span %html;>
<!ATTLIST span
  class CDATA #IMPLIED
>
<!ELEMENT ul (li*)>
<!ELEMENT li (#PCDATA)>

<!ELEMENT createdEntities (values,description)>
<!ELEMENT createdRelations (values,description)>
<!ELEMENT values (#PCDATA)>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/j2ee/aim.struts.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='j2ee' subtech='struts' descriptor='j2ee/aim.struts.xml' label='Models Struts framework artifacts'>
  <description>
    Process Struts framework artifacts. Struts XML descriptors (struts-config.xml)
    and references to Struts actions in JSP files are currently processed.
  </description>

  <dependencies>
    <dependency>j2ee/java</dependency>
  </dependencies>

  <properties>
    <property id='aim.struts.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>
        If true, Struts XML descriptors are processed.
      </description>
    </property>

    <property id='aim.struts.software' type='string'>
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>
        The default (fallback) software name.
        Please note that global software resolvers could be used to resolve the software where each Struts artifact lives.
      </description>
    </property>

    <property id='aim.struts.overrideSoftwareResolver' type='bool'>
      <name>overrideSoftwareResolver</name>
      <example>true</example>
      <description>
        If true, use the software detected in web.xml descriptor, if any.
        If false, use standard software resolution.
      </description>
    </property>

    <property id='aim.struts.filter' type='list' subtype='antPattern'>
      <name>filter</name>
      <example>**/*struts-config.xml</example>
      <description>
        Ant patterns for Struts XML descriptors.
      </description>
    </property>

    <property id='aim.struts.jsp.rule.active' type='bool'>
      <name>jspActive</name>
      <example>false</example>
      <description>
        If true, references in JSP pages to Struts elements are processed.
      </description>
    </property>

    <property id='aim.struts.jsp.filter' type='list' subtype='antPattern'>
      <name>filter</name>
      <example>**/*.jsp,**/*.jspx</example>
      <description>
        Ant patterns to choose which JSP pages to process for references to Struts elements.
      </description>
    </property>

  </properties>

  <createdEntities>
    <values>configuration,element(form|action|forward),class,page</values>
    <description>
      Each Struts descriptor is modeled as <i>configuration</i>. Each Struts entity (form, action, forward or
      redirection) is modeled as an <i>element</i>. Implementing classes (or target JSP pages) are modeled
      as <i>class</i> or <i>page</i>, respectively.
    </description>
  </createdEntities>

  <createdRelations>
    <values>software-configuration->configuration,element-configuration->configuration,element-uses|implementedBy|usesForm->class,element-forwards|redirects->element|page</values>
    <description>
      Each element is related (<i>configuration</i> relation) to Struts descriptor that declares it.
      Relations (<i>uses</i>, <i>implementedBy</i>, <i>usesForm</i>, <i>forwards</i> or <i>redirects</i> are
      created between the Struts <i>element</i> and the target (<i>class</i>, <i>page</i> or <i>element</i>).
    </description>
  </createdRelations>

  <importantConfigurations activation="aim.struts.rule.active">
    <alternative><value>aim.struts.jsp.rule.active=true</value></alternative>
  </importantConfigurations>

</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/cpp/aim.cpp.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='cpp' subtech='cpp' descriptor='cpp/aim.cpp.xml' label=''>
  <description>
  This module identifies C/C++ files and adds to the model
  the source file, classes, structs and methods.
  </description>

  <dependencies/>

  <properties>
    <property id='aim.cpp.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>
        Rule activation flag.
      </description>
    </property>

    <property id='aim.cpp.proc.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>
        Activate rule to extract relations between C++ and DB objects.
      </description>
    </property>

    <property id="aim.cpp.software" type="string">
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>
        Containing software for program entities discovered by C++ rule.
        Used as fallback if no global resolver or global resolver cannot find a containing software for the target entity.
      </description>
    </property>

    <property id='aim.cpp.filter' type='enum'>
      <name>filter</name>
      <example>pattern</example>
      <description>Strategy to use for selecting C++ files to process.</description>
      <possible>
        <enumval name='default'>Accept language extensions for cpp technology.</enumval>
        <enumval name='pattern'>Accept scripts matching patterns in the <code>patterns</code> property.</enumval>
      </possible>
    </property>

    <property id='aim.cpp.filter.pattern' type='list' subtype='antPattern'>
      <name>pattern</name>
      <example>**/*.cpp,**/*.cc</example>
      <description>If <code>filter=pattern</code>, use the following comma-separated Ant patterns for matching JCL files.</description>
    </property>

    <property id='aim.cpp.level' type='enum'>
      <name>level</name>
      <example>file</example>
      <description>Level of components generated by the rule on model.</description>
      <possible>
        <enumval name='file'>Generates at resource level.</enumval>
        <enumval name='class'>Generates resources and classes.</enumval>
        <enumval name='function'>Generates resources, classes and functions.</enumval>
      </possible>
    </property>

    <property id='aim.cpp.rule.resolveCalls' type='bool'>
      <name>resolveCalls</name>
      <example>false</example>
      <description>Resolve method calls</description>
    </property>

    <property id='aim.cpp.rule.resolveInheritance' type='bool'>
      <name>resolveInheritance</name>
      <example>false</example>
      <description>Resolve class inheritance</description>
    </property>

    <property id='aim.cpp.rule.resolveTypeReferences' type='bool'>
      <name>resolveTypeReferences</name>
      <example>false</example>
      <description>Resolve type references</description>
    </property>

    <property id='aim.cpp.resolver' type='enum'>
      <name>resolver</name>
      <example>existing</example>
      <description>Indicates resolver to use in order to generate model.</description>
      <possible>
        <enumval name='existing'>Resolve only relations to classes in same model.</enumval>
      </possible>
    </property>

    <property id='aim.cpp.proc.allclasses' type='bool'>
      <name>resolver</name>
      <example>existing</example>
      <description>Set true if we want to add all classes (even those with no relations to PL/SQL sentences) to the model.</description>
    </property>

    <property id='aim.cpp.ignored.calls.same.object' type='bool'>
      <name>ignored.calls.same.object</name>
      <example>false</example>
      <description>If true calls to same object are ignored.</description>
    </property>
  </properties>

  <createdEntities>
    <values>program,class,operation,structs</values>
    <description>If <code>aim.cpp.level=file</code> creates C++ programs and, if <code>aim.cpp.level=class</code>, will create C++ class.
     If <code>aim.cpp.level=function</code>, will create structs and functions also</description>
  </createdEntities>

  <createdRelations>
    <values>application-contains-&gt;program,application-contains-&gt;class,program-contains-&gt;struct,program-contains-&gt;operation</values>
    <description>Resolves class (<code>aim.cpp.level=class</code>), programs contained in an application, but also structs and operations contained in a program (<code>aim.cpp.level=function</code>).</description>
  </createdRelations>

  <importantConfigurations>
    <alternative>
      <value>aim.cpp.rule.active=true</value>
      <value>aim.cpp.level=file</value>
    </alternative>
    <alternative>
      <value>aim.cpp.rule.active=true</value>
      <value>aim.cpp.level=class</value>
    </alternative>
    <alternative>
      <value>aim.cpp.rule.active=true</value>
      <value>aim.cpp.level=function</value>
    </alternative>
  </importantConfigurations>
</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/database/aim.db2.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='database' subtech='db2' descriptor='database/aim.db2.xml' label='Process DB2/SQL code'>
  <description>
    Process DB2/SQL code.
    <br/>
    Analyze sql files and models entities and dependencies found.
    <br/>
    Database entities are located in a schema. Different schema resolution strategies could be used,
    related to the location of the sql file.
  </description>

  <properties>
    <property id='aim.db2.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>
        If true, DB2/SQL code will be processed.
      </description>
    </property>

    <property id='aim.db2.database' type='string'>
      <name>database</name>
      <example>${aim.common.database.dbsystem}</example>
      <description>
        The default database.
      </description>
    </property>

    <property id='aim.db2.schema' type='string'>
      <name>schema</name>
      <example>${aim.common.database.dbname}</example>
      <description>
        The default schema, to use when the schema cannot be resolved.
      </description>
    </property>

    <property id='aim.db2.filter' type='enum'>
      <name>filter</name>
      <example>default</example>
      <description>
        Which files to analyze. Use the default filter (based on extensions in language info) or explicit patterns.
      </description>
      <possible>
        <enumval name="default">Uses the extensions configured in checKing for db2 technology.</enumval>
        <enumval name="pattern">Uses patterns in <code>pattern</code> property.</enumval>
      </possible>
    </property>

    <property id='aim.db2.filter.pattern' type='list' subtype='antPattern'>
      <name>pattern</name>
      <example>**/*.sql</example>
      <description>
        Pattern for DB2/SQL sources (used if filter set to pattern).
      </description>
    </property>

    <property id='aim.db2.modelStatements' type='bool'>
      <name>ignoreCaseColumns</name>
      <example>false</example>
      <description>
        If true DML statements will be modeled as entities.
      </description>
    </property>

  </properties>

  <createdEntities>
    <values>
      database,databaseInstance,table,view,sequence,synonym,index,primaryKey,dblink,other(package),
      storedProcedure(procedure|function),userType
    </values>
    <description>
      Generates a software (database) for the database instance, and a component (databaseInstance) for the schema.
      <br/>
      On the databaseInstance container the rest of database entities are added:
      tables, views, primary keys, indexes, synonym, sequence, trigger, package, stored procedure / function, db-link.
      <br/>
      Note: An Oracle package is modeled as <code>other</code> with db2Type=package.
      <br/>
      The <code>sqlType</code> property and  <code>db2Type</code> property contains the entity type.
    </description>
  </createdEntities>

  <importantConfigurations activation="aim.db2.rule.active" />

</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/abap/aim.abap.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='abap' subtech='abap' descriptor='abap/aim.abap.xml' label='Process SAP/R3 (ABAP) technology'>
  <description>
    Process SAP/R3 (ABAP IV) technology. ABAP sources are processed to extract entities (for both procedural
    and class-oriented paradigms) and dependencies are resolved.
  </description>

  <properties>
    <property id="aim.abap.rule.active" type="bool">
      <name>abap.rule.active</name>
      <example>true</example>
      <description>If true, process ABAP source code.</description>
    </property>

    <property id="aim.abap.software" type="string">
      <name>software</name>
      <example>${aim.common.software}</example>
      <description>
        Containing software for program entities discovered by ABAP rule.
        Used as fallback if no global resolver or global resolver cannot find a containing software for the target entity.
      </description>
    </property>

    <property id="aim.abap.dbsystem" type="string">
      <name>dbsystem</name>
      <example>SAP/R3</example>
      <description>
        The container fo referenced non-internal tables (e.g. SAP/R3).
        Used as fallback if no global database object resolver, or the resolver cannot find the target entity.
      </description>
    </property>

    <property id="aim.abap.dbname" type="string">
      <name>dbname</name>
      <example>SAP</example>
      <description>
        The database name or database schema (e.g. SAP) for container of referenced non-internal tables.
        Used as fallback if no global database object resolver, or the resolver cannot find the target entity.
      </description>
    </property>

    <property id="aim.abap.createSqlNodes" type="bool">
      <name>createSqlNodes</name>
      <example>true</example>
      <description>If true, SQL intermediate components are created between source and destination database objects.</description>
    </property>

    <property id="aim.abap.processInternalTables" type="bool">
      <name>processInternalTables</name>
      <example>false</example>
      <description>If true, internal tables declarations and usages are registered in the model.</description>
    </property>

    <property id="aim.abap.registerTableReferences" type="bool">
      <name>registerTableReferences</name>
      <example>false</example>
      <description>If true, TABLES references to ABAP tables are registered.</description>
    </property>

    <property id="aim.abap.registerSapCalls" type="bool">
      <name>registerSapCalls</name>
      <example>true</example>
      <description>If true, calls to standard SAP procedures (functions, methods, transactions) are registered; ignored otherwise.</description>
    </property>

    <property id="aim.abap.filter" type="enum">
      <name>filter</name>
      <example>default</example>
      <description>Strategy to use for selecting ABAP files to process.</description>
      <possible>
        <enumval name="default">Use extensions in language info.</enumval>
        <enumval name="pattern">Uses explicit pattern.</enumval>
      </possible>
    </property>

    <property id="aim.abap.filter.pattern" type="list" subtype="antPattern">
      <name>filter.pattern</name>
      <example>*.abap,**/*.abap</example>
      <description>If filter set to pattern, use the following comma-separated patterns</description>
    </property>

    <property id="aim.abap.repository.dir" type="string">
      <name>repository.dir</name>
      <example>${CHECKING_DATA}/ABAP_REPO</example>
      <description>(Optional) path to the directory where repository files generated by extractor utility are stored.</description>
    </property>

  </properties>

  <createdEntities>
    <values>
      program(report,program), class, method, operation(form,function,module), transaction, dynpro,
      dataset, module(function-pool, type-pool, class-pool, interface-pool), table(internalTable, sapTable)
    </values>
    <description>
      Creates program component for both ABAP report and program, or class. Creates a module component
      for ABAP containers (function/type/class/interface pools), and a component for each referenced
      ABAP/SAP entity (dataset, transaction, dynpro or table).
      <br/>
      All procedural units (form, module, function or method) referenced in ABAP sources are registered.
      <br/>
      Both internal and external (SAP or custom) tables are registered.
    </description>
  </createdEntities>

  <createdRelations>
    <values>
      software|group-contains->program|operation|class,
      program|class-contains->operation|method,
      program|operation|method-calls->transaction
      program|operation|method-calls->operation|method,
      program-calls->dynpro,
      program|operation|method-uses->dataset,
      program|operation|method-uses(different kinds)->table
    </values>
    <description>
      Process relations between ABAP entities. Calls to procedural units are registered.
      Usages of datasets, dynpros and internal/external tables are modelled as relations
      (calls, uses, select, etc.).
    </description>
  </createdRelations>

</block>

=== ianjchauhan/kiuwanUpload/resources/appmap/configurations/modelbuilder/_DEFAULT_/legacy/aim.jcl.descriptor.xml
<!DOCTYPE block SYSTEM "../aim.configuration.dtd">
<block tech='legacy' subtech='jcl' descriptor='legacy/aim.jcl.xml' label='Process Job Control Language (JCL) code'>
  <description>
    Process Job Control Language (JCL) code.
  </description>

  <properties>

    <property id='aim.jcl.rule.active' type='bool'>
      <name>active</name>
      <example>false</example>
      <description>Enables processing of JCL code.</description>
    </property>

    <property id='aim.jcl.software.batch' type='string'>
      <name>batch</name>
      <example>${aim.common.software}</example>
      <description>Application/module name for JCL scripts.</description>
    </property>

    <property id='aim.jcl.software.backend' type='string'>
      <name>backend</name>
      <example>${aim.common.software}</example>
      <description>Application/module name for called programs, not resolved as JCL scripts.</description>
    </property>

    <property id='aim.jcl.filter' type='enum'>
      <name>filter</name>
      <example>default</example>
      <description>Strategy to use for selecting JCL files to process.</description>
      <possible>
        <enumval name='default'>Accept language extensions for jcl technology.</enumval>
        <enumval name='pattern'>Accept scripts matching patterns in the <code>patterns</code> property.</enumval>
      </possible>
    </property>

    <property id='aim.jcl.filter.pattern' type='list' subtype='antPattern'>
      <name>pattern</name>
      <example>**/*.jcl</example>
      <description>If <code>filter=pattern</code>, use the following comma-separated Ant patterns for matching JCL files.</description>
    </property>

    <property id='aim.jcl.ignoreCase' type='string'>
      <name>ignoreCase</name>
      <example>${aim.common.ignoreCase}</example>
      <description>If true, case is ignored in entity names referenced in JCL scripts.</description>
    </property>

    <property id="aim.jcl.acceptUnresolved" type="bool">
      <name>acceptUnresolved</name>
      <example>${aim.common.acceptUnresolved}</example>
      <description>If true, target called programs not found in model are created (in batch application). If false, unresolved calls are ignored.</description>
    </property>

    <property id="aim.jcl.saveStepInformation" type="bool">
      <name>saveStepInformation</name>
      <example>true</example>
      <description>If true, be mapped so many relationships between the JCL and the element as are referred to in various steps. If false, be mapped a single relationship between JCL and the element although references the element more than once inside.</description>
    </property>

    <property id="aim.jcl.instream" type="bool">
      <name>instream</name>
      <example>true</example>
      <description>If true, internal procedures are modeled</description>
    </property>

    <property id="aim.jcl.visitor" type="string">
      <name>visitor</name>
      <example>E</example>
      <description>Type of node visitor</description>
      <possible>
        <enumval name='E'>Use extended visitor.</enumval>
        <enumval name='D'>Use default visitor.</enumval>
      </possible>
    </property>

    <property id="aim.jcl.resolver.progcalls.registerUnresolvedCalls" type="bool">
      <name>registerUnresolvedCalls</name>
      <example>${aim.common.acceptUnresolved}</example>
      <description>If true, calls to programs that cannot be found are registered without language / artifact properties. If false, such calls are ignored.</description>
    </property>

    <property id="aim.jcl.resolver.file.extensions" type="string">
      <name>file.extensions</name>
      <example>jcl,prc,ctc</example>
      <description>Extensions to consider for called files</description>
    </property>

    <property id="aim.jcl.resolver.cobol.extensions" type="list" subtype="string">
      <name>cobol.extensions</name>
      <example>cob,cbl,cobol,pco</example>
      <description>Extensions to consider for called cobol programs</description>
    </property>

    <property id="aim.jcl.registerUtilities" type="bool">
      <name>registerUtilities</name>
      <example>true</example>
      <description>If true, utilities called are registered. If false, utilities are not modelled as components and no calls relation is created.</description>
    </property>

    <property id="aim.jcl.resolveSqlStatements" type="bool">
      <name>resolveSqlStatements</name>
      <example>true</example>
      <description>If true, SQL statements passed to DB2 utilities are processed. If false, SQL statements in JCL code are ignored.</description>
    </property>

    <property id="aim.jcl.addQuery" type="bool">
      <name>addQuery</name>
      <example>true</example>
      <description>If set to true, SQL queries and their relationships with used tables are inserted into the model as explicit entities. If false, direct relations between JCL and used tables are presented.</description>
    </property>

    <property id="aim.jcl.addSqlCode" type="bool">
      <name>addSqlCode</name>
      <example>true</example>
      <description>If set to true, SQL code is added as property into the queries. Ignored if addQuery=false.</description>
    </property>

    <property id="aim.jcl.utilities.toIgnore" type="list" subtype="string">
      <name>utilities.toIgnore</name>
      <example>IDCAMS, IEBCOPY, IEBDG, IEBGENER, IEBUPDTE, IEFBR14, ICEGENER, SORT, SORTD, ICEMAN, ICKDSF, IEHINITT, IEHLIST, IEHPROGM, SPZAP</example>
      <description>Comma-separated list of system programs / procedures to ignore</description>
    </property>

    <property id="aim.jcl.utilities.host" type="list" subtype="string">
      <name>utilities.host</name>
      <example>IKJEFT01, IKJEFT1A, IKJEFT1B</example>
      <description>Comma-separated list of host utilities (used to execute programs and launch DB2 utilities)</description>
    </property>

    <property id="aim.jcl.utilities.db2" type="list" subtype="string">
      <name>utilities.db2</name>
      <example>DSNTIAUL, DSNTIAD, DSNTEP2, DSNTEP4, DSNTIAUP</example>
      <description>Comma-separated list of DB2 utilities, used to execute SQL statements (or table LOAD/UNLOAD)</description>
    </property>

    <property id="aim.jcl.utilities.controlm" type="list" subtype="string">
      <name>utilities.controlm</name>
      <example>CTMJOB, CTMPLANB</example>
      <description>Comma-separated list of Control-M utilities for launching/scheduling Control-M jobs from JCL</description>
    </property>

    <property id='aim.jcl.dbsystem' type='string'>
      <name>dbsystem</name>
      <example>${aim.common.database.dbsystem}</example>
      <description>
        The database type (e.g. DB2) or database name for container of referenced tables.
        Used as fallback if no global database object resolver, or the resolver cannot find the target entity.
      </description>
    </property>

    <property id='aim.jcl.dbname' type='string'>
      <name>dbname</name>
      <example>${aim.common.database.dbname}</example>
      <description>
        The database name or database schema for container of referenced tables.
        Used as fallback if no global database object resolver, or the resolver cannot find the target entity.
      </description>
    </property>

  </properties>

  <createdEntities>
    <values>program (jcl or cobol), operation (procedure), resource (file), utility, sql, table</values>
    <description>
      Creates <i>program</i> components for each JCL job, and for each called cobol programs.<br/>
      Creates <i>operation</i> components for each procedure (instream or cataloged procedures).<br/>
      Creates <i>resource</i> components for each called file (i.e. ctc files).<br/>
      Creates <i>utility</i> components for utilities called to execute DB2 programs (i.e. IKJEFT01, IKJEFT1A or IKJEFT1B).
      Creates <i>sql</i> and <i>table</i> components for dependencies on DB2 tables (when resolveSqlStatements is true).
    </description>
  </createdEntities>

  <createdRelations>
    <values>
      program -contains-> operation,
      operation -contains-> operation,
      program -calls-> program,
      operation -calls-> program,
      program -calls-> operation,
      operation -calls-> operation,
      program -calls-> utility,
      program -calls-> utility,
      program -uses-> resource,
      operation -uses-> resource,
      program|operation -uses-> sql,
      sql -select|insert|update|delete-> table
    </values>
    <description>
      Creates a <i>calls</i> relation between the jcl job program or procedure (operation) and the called program, procedure or utility.<br/>
      Creates a <i>uses</i> relation between the jcl job program or procedure (operation) and the called file.<br/>
      Creates a <i>contains</i> relation between the jcl job program or procedure (operation) and the declared procedure.<br/>
      Creates relations between job/procedure and DB2 tables, with intermediate query objects.
    </description>
  </createdRelations>

  <importantConfigurations activation="aim.jcl.rule.active">
    <alternative><value>aim.jcl.instream=false</value></alternative>
    <alternative><value>aim.jcl.saveStepInformation=false</value></alternative>
  </importantConfigurations>

</block>
